paths:
  /search:
    get:
      summary: Busca oportunidades de contrato
      operationId: getOpportunities
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
          description: Clave API para autenticación.
        - name: postedFrom
          in: query
          required: true
          schema:
            type: string
            format: date
            example: "01/01/2024"
          description: Fecha de inicio en formato MM/DD/YYYY.
        - name: postedTo
          in: query
          required: true
          schema:
            type: string
            format: date
            example: "12/31/2024"
          description: Fecha de fin en formato MM/DD/YYYY.
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 1000
          description: Límite de resultados.
